### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by klihelp** [cedaro/cpt-archives#2]
How to get Archive page content?
``the_archive_description();``

How to get Archive page thumbnail support?
how to get this one?

**Comment by klihelp** [comment]
Get the Archive Page ID

```
global $cptarchives;
if ( isset($cptarchives) && is_object($cptarchives) ) {
  $archive = $cptarchives->get_archive();
  $postid = $archive->get_post_id();
}
```

**Comment by bradyvercher** [comment]
Thanks for the suggestions @klihelp. I added a section to the docs to cover most of those scenarios.

As far as getting the archive post ID, you can use `$cptarchives->get_archive_id()` for brevity. It should also be possible to chain the calls, so this would work, too: `$cptarchives->get_archive()->get_post_id()`.

**Comment by klihelp** [comment]
Would it be easier to have the global cptarchives() function, instead $cptarchives global variable.

```
global $cptarchives;
if ( isset($cptarchives) && is_object($cptarchives) ) 
```
VS
```if ( function_exist('cptarchives) && is_object($cptarchives) ) ```

**Comment by klihelp** [comment]
``` 
> $cptarchives->get_archive()->get_post_id().```

The reason for the type checking is that ```$cptarchives->get_archive()``` sometimes return as non-object.

**Comment by bradyvercher** [comment]
The only time it doesn't return an object should be when an archive hasn't been registered. Did you run into any scenarios where that isn't the case?

**Comment by klihelp** [comment]
yes: https://github.com/cedaro/cpt-archives/issues/4

**Comment by bradyvercher** [comment]
I would think the `isset()` check should be enough, rather than having to use `is_object()` as well. That should be shorter than the `function_exists()` check, too.

Do you run into any issues if you don't use the `is_object()` check?

I've used the function method before and can see the benefit, it just feels strange to define a function that's nothing more than a wrapper for a global variable.

Otherwise, you can create a custom function similar to the one WordPress uses for checking if the Customizer is active: https://github.com/WordPress/WordPress/blob/3f448d7cd5752eb4eb83c15ded25ae4f1cee31cc/wp-includes/theme.php#L2095-L2108

**Comment by klihelp** [comment]
>> I've used the function method before and can see the benefit, it just feels strange to define a function that's nothing more than a wrapper for a global variable.
I am just learning from older plugins; as Wocommerce have WC(),  Eazyest Gallery have eazyest_gallery(), Advanced Custom Field have get_field() ...
